/**
 * Shonari-Portfolio content — Wildy-inspired structure
 * Reach pass for Coder (Featured vs Manga + Adobe blurbs)
 * Drop into src/content/site.ts; wire filters/routes on Nesta.
 *
 * Chief/Reach hygiene:
 * - Case "More work" / related: same `lane` only (never arbitrary slice).
 * - needsAsset: true → DZ/Arty must drop file at `image` path before Featured ships that thumb.
 * - homepageCurated: Manga / Photo / Video homepage strips only; full sets in archive filters.
 * - Featured stays locked (trim1); do not add Photo/Video to featured[].
 * - Fan decks: manga.fanDecks = 4 themes × 4 stills (Manga / Harmony / Prints / Universal = 16). Photo/Video = flat. No videos in fans.
 * - printArchive: All Works Print lane = Homage 25–28 (Sep 25 Drive pull, lead) + Prints 01–17 + Homage 01–24 + unique manga stills (lightbox like Photography).
 * - mangaArchive: All Works Manga lane = Homage 01–24 + vault manga + unique /work/deck/ fills (no Prints; lightbox like Photo/Print).
 * - productionArchive: All Works Production lane = Adobe Professional Production pro/01–19 (no tees; lightbox like Photo/Print/Manga).
 * - workFilters: All Works tabs omit Design; disciplines keeps Design for hero rotator (Chief course-correct 2026-09-18).
 * - audio: muted-first Journeys bed at /work/audio/journeys-bed.mp3 (Chief lock 2026-09-18).
 * - Thin Featured cases: deep-link CTA to `adobe` until multi-image case pages exist.
 */

export const site = {
  name: "Shonari Phillips",
  title: "Graphic Designer",
  mantra: "Die with Memories, Not Dreams",
  tagline:
    "Graphic designer for print, signage, and apparel, from concept through production. Currently at Biz Printing USA.",
  email: "shonarip@gmail.com",
  location: "Tamarac, FL",
  adobe: "https://shonarip.myportfolio.com/",

  /** Wildy-style hero rotator */
  disciplines: ["Design", "Production", "Manga", "Print", "Photography", "Videography"] as const,
  /** All Works tabs only — Design lane projects under All, not a separate tab (Chief 2026-09-18) */
  workFilters: ["Production", "Manga", "Print", "Photography", "Videography"] as const,

  resume: "/resume.pdf?v=resume-oct5",

  /** First screen: name, what I do, and a clear path to the work. */
  hero: {
    eyebrow: "Graphic designer · Tamarac, FL",
    headline: "Shonari Phillips",
    summary: "I design print, signage, and apparel, and take each piece from first concept through production.",
    context: "Currently a graphic designer at Biz Printing USA.",
    primary: { label: "View my work", href: "/portfolio" },
    secondary: { label: "Get in touch", href: "/contact" },
    /** Quick paths into the archive, one per discipline. */
    lanes: [
      { label: "Production", href: "/work?lane=Production" },
      { label: "Print", href: "/work?lane=Print" },
      { label: "Manga", href: "/work?lane=Manga" },
      { label: "Photography", href: "/work?lane=Photography" },
      { label: "Videography", href: "/work?lane=Videography" },
    ],
  },

  /** /work page header copy (replaces hardcoded intro in work/page.tsx) */
  workIndex: {
    heading: "All works",
    intro: "Every piece, grouped by discipline. Open any image to see it full size. The full project stories are on the Portfolio page.",
    backLabel: "Back to Portfolio",
    backHref: "/portfolio",
  },

  /** /contact page — contact, about, resume. Never add a phone number. */
  contactPage: {
    title: "Contact",
    intro: "Email is the fastest way to reach me. I'm based in Tamarac, FL, and open to print, signage, apparel, and brand work.",
    resumeLabel: "View Resume",
    resumeNote: "Opens as a PDF in a new tab.",
  },

  nav: [
    { label: "Work", href: "/portfolio" },
    { label: "All works", href: "/work" },
    { label: "About", href: "/contact#about" },
    { label: "Resume", href: "/resume.pdf?v=resume-oct5", external: true },
  ],

  about: {
    heading: "About",
    paragraphs: [
      "I'm Shonari Phillips, a graphic designer in Tamarac, FL. I design print, signage, and apparel and take it through production. I'm currently at Biz Printing USA. Before that I was the sole designer at FASTSIGNS Indianapolis, turning out 35–50 designs a week for clients including Century 21 and Live Nation, and I started at Kingdom Workshop in Fort Lauderdale, designing and producing apparel, signs, and vehicle wraps in-house.",
      "Through creating, I give purpose to things that might seem purposeless. Graphic design is not only imagery — it is a way to let a viewer grasp a psyche. My love for Japanese visual culture spans years; Homage to Nihon is where I extract the essence of panels and characters and refuse to make the same design twice.",
      "Die with Memories, Not Dreams. Cool mask over soft heartbreak. Night-sky stages for work that wants to glow.",
    ],
  },

  /**
   * Featured strip (Wildy: 2–3 + VIEW PROJECT)
   * Case routes: /work/[slug]
   */
  featured: [
    {
      slug: "physical-production",
      title: "Physical Production",
      year: "2026",
      caption: "Apparel & signage",
      role: "Print × Signage × Apparel",
      lane: "Production",
      description:
        "Signage, vehicle graphics, banners, business cards, and apparel, designed and taken through production for paying clients.",
      caseStudy: {
        client: "Businesses across the Indianapolis and Fort Lauderdale metro areas",
        role: "Lead Graphic Designer",
        tools: "Adobe Creative Suite, Photoshop, Illustrator",
        deliveredFor: ["Indianapolis Museum of Art", "Century 21", "Carpenter Insurance", "Car dealerships", "Home retail brands"],
        summary: "I'm a graphic designer at Biz Printing USA in Tamarac, designing banners, business cards, flyers, yard signs, and print-and-mail pieces through to press. At FASTSIGNS Indianapolis I was the sole designer, turning out 35–50 designs a week, with production-ready vinyl and graphics for vehicles, substrates, and buildings. At Kingdom Workshop in Fort Lauderdale I designed apparel, signs, and vehicle wraps and produced them in-house.",
      },
      tags: ["Merch", "Print", "Brand", "Production"],
      href: "/work/physical-production",
      adobe: "https://shonarip.myportfolio.com/physical-production",
      image: "/work/physical/pro/02-presidential-touch-limo.jpg",
            images: [
        "/work/physical/pro/02-presidential-touch-limo.jpg",
        "/work/physical/pro/01-kylen-granson-books.png",
        "/work/physical/pro/03-smackem-gooz-menu.jpg",
        "/work/physical/tee-02-girls-trips-nobg.png",
        "/work/physical/tee-01-zoom-nobg.png",
        "/work/physical/zoom-shirt-nobg.png",
        "/work/physical/tee-03-bhm-faith-nobg.png",
        "/work/physical/51-shirt-nobg.png",
        "/work/physical/tee-06-teacher-shirt-nobg.png",
        "/work/physical/pro/04-pro-04-d7dbf12d.jpg",
        "/work/physical/pro/05-pro-05-de3e0287.jpg",
        "/work/physical/pro/06-zoom-shirt.png",
        "/work/physical/pro/07-pro-07-9a95f687.jpg",
        "/work/physical/pro/08-pro-08-55c88388.png",
        "/work/physical/pro/09-pro-09-efa9fffd.jpg",
        "/work/physical/pro/10-pro-10-87a806ac.png",
        "/work/physical/pro/11-pro-11-a2880d77.jpg",
        "/work/physical/pro/12-pro-12-837cbdde.png",
        "/work/physical/pro/13-pro-13-62cff7a7.png",
        "/work/physical/pro/14-pro-14-1b40528b.jpg",
        "/work/physical/pro/15-pro-15-146fb7a1.png",
        "/work/physical/pro/16-pro-16-b71bead9.png",
        "/work/physical/pro/17-pro-17-60e44d64.png",
        "/work/physical/pro/18-pro-18-c48bbe25.png",
        "/work/physical/pro/19-pro-19-af10fe90.png",
      ],
      cta: "View project",
    },
    {
      slug: "homage-to-nihon",
      title: "Homage to Nihon",
      year: "2024",
      caption: "Manga edits",
      role: "Art Direction × Manga Edits",
      lane: "Manga",
      description:
        "Creative takes on favorite manga panels and anime characters — extracting what the image represents, never repeating a design. Emotion through the motionless.",
      caseStudy: {
        client: "Personal series",
        role: "Art direction and manga edits",
        tools: "Adobe Creative Suite, Photoshop, Illustrator",
        deliveredFor: [],
        summary: "Homage to Nihon is an ongoing series of edits of manga panels and anime characters. Each piece pulls out what the original image stands for, and no design is repeated.",
      },
      tags: ["Manga", "Edit", "Japan"],
      href: "/work/homage-to-nihon",
      adobe: "https://shonarip.myportfolio.com/homage-to-nihon",
      image: "/work/homage/thumb-fermenting.jpg",
      images: [
        "/work/homage/25-cyber-ranma.jpg",
        "/work/homage/26-4-ur-eyez.jpg",
        "/work/homage/27-mei-mei.jpg",
        "/work/homage/28-contained.jpg",
        "/work/homage/01.jpg",
        "/work/homage/02.png",
        "/work/homage/03.png",
        "/work/homage/04.png",
        "/work/homage/05.png",
        "/work/homage/06.png",
        "/work/homage/07.png",
        "/work/homage/08.png",
        "/work/homage/09.png",
        "/work/homage/10.png",
        "/work/homage/11.png",
        "/work/homage/12.png",
        "/work/homage/13.png",
        "/work/homage/14.jpg",
        "/work/homage/15.jpg",
        "/work/homage/16.jpg",
        "/work/homage/17.jpg",
        "/work/homage/18.jpg",
        "/work/homage/19.jpg",
        "/work/homage/20.png",
        "/work/homage/21.jpg",
        "/work/homage/22.jpg",
        "/work/homage/23.png",
        "/work/homage/24.png",
      ],
      cta: "View project",
    }
  ],

  /** Full archive for workFilters (Production / Manga / Print; Design-lane projects under All only) */
  projects: [
    {
      slug: "homage-to-nihon",
      title: "Homage to Nihon",
      year: "2024",
      caption: "Manga edits",
      role: "Art Direction × Manga Edits",
      lane: "Manga",
      featured: true,
      description:
        "Creative takes on favorite manga panels and anime characters — extracting essence, never the same design twice.",
      caseStudy: {
        client: "Personal series",
        role: "Art direction and manga edits",
        tools: "Adobe Creative Suite, Photoshop, Illustrator",
        deliveredFor: [],
        summary: "Homage to Nihon is an ongoing series of edits of manga panels and anime characters. Each piece pulls out what the original image stands for, and no design is repeated.",
      },
      tags: ["Manga", "Edit", "Japan"],
      href: "/work/homage-to-nihon",
      adobe: "https://shonarip.myportfolio.com/homage-to-nihon",
      image: "/work/homage/thumb-fermenting.jpg",
      images: [
        "/work/homage/25-cyber-ranma.jpg",
        "/work/homage/26-4-ur-eyez.jpg",
        "/work/homage/27-mei-mei.jpg",
        "/work/homage/28-contained.jpg",
        "/work/homage/01.jpg",
        "/work/homage/02.png",
        "/work/homage/03.png",
        "/work/homage/04.png",
        "/work/homage/05.png",
        "/work/homage/06.png",
        "/work/homage/07.png",
        "/work/homage/08.png",
        "/work/homage/09.png",
        "/work/homage/10.png",
        "/work/homage/11.png",
        "/work/homage/12.png",
        "/work/homage/13.png",
        "/work/homage/14.jpg",
        "/work/homage/15.jpg",
        "/work/homage/16.jpg",
        "/work/homage/17.jpg",
        "/work/homage/18.jpg",
        "/work/homage/19.jpg",
        "/work/homage/20.png",
        "/work/homage/21.jpg",
        "/work/homage/22.jpg",
        "/work/homage/23.png",
        "/work/homage/24.png",
      ],
    },
    {
      slug: "eyes-of-the-beholder",
      title: "Eyes of the Beholder",
      year: "2024",
      caption: "Early work",
      role: "Graphic Series",
      lane: "Design",
      featured: false,
      description:
        "Earlier works collected as a chapter — foundations of eye, mood, and graphic instinct before the later systems.",
      tags: ["Graphic", "Archive"],
      href: "/work/eyes-of-the-beholder",
      adobe: "https://shonarip.myportfolio.com/eyes-of-the-beholder",
      image: "/work/floral-bg.png",
    },
    {
      slug: "branding",
      title: "Branding",
      year: "2024",
      caption: "Logos & identity",
      role: "Identity × Systems",
      lane: "Design",
      featured: false,
      description:
        "Brand marks and visual systems — identity work built for recognition at a glance and consistency across touchpoints.",
      tags: ["Brand", "Identity"],
      href: "/work/branding",
      adobe: "https://shonarip.myportfolio.com/branding",
      image: "/work/branding-mark.jpg",
    },
    {
      slug: "physical-production",
      title: "Physical Production",
      year: "2026",
      caption: "Apparel & signage",
      role: "Print × Signage × Apparel",
      lane: "Production",
      featured: true,
      description:
        "Signage, vehicle graphics, banners, business cards, and apparel, designed and taken through production for paying clients.",
      caseStudy: {
        client: "Businesses across the Indianapolis and Fort Lauderdale metro areas",
        role: "Lead Graphic Designer",
        tools: "Adobe Creative Suite, Photoshop, Illustrator",
        deliveredFor: ["Indianapolis Museum of Art", "Century 21", "Carpenter Insurance", "Car dealerships", "Home retail brands"],
        summary: "I'm a graphic designer at Biz Printing USA in Tamarac, designing banners, business cards, flyers, yard signs, and print-and-mail pieces through to press. At FASTSIGNS Indianapolis I was the sole designer, turning out 35–50 designs a week, with production-ready vinyl and graphics for vehicles, substrates, and buildings. At Kingdom Workshop in Fort Lauderdale I designed apparel, signs, and vehicle wraps and produced them in-house.",
      },
      tags: ["Merch", "Print", "Brand", "Production"],
      href: "/work/physical-production",
      adobe: "https://shonarip.myportfolio.com/physical-production",
      image: "/work/physical/pro/02-presidential-touch-limo.jpg",
            images: [
        "/work/physical/pro/02-presidential-touch-limo.jpg",
        "/work/physical/pro/01-kylen-granson-books.png",
        "/work/physical/pro/03-smackem-gooz-menu.jpg",
        "/work/physical/tee-02-girls-trips-nobg.png",
        "/work/physical/tee-01-zoom-nobg.png",
        "/work/physical/zoom-shirt-nobg.png",
        "/work/physical/tee-03-bhm-faith-nobg.png",
        "/work/physical/51-shirt-nobg.png",
        "/work/physical/tee-06-teacher-shirt-nobg.png",
        "/work/physical/pro/04-pro-04-d7dbf12d.jpg",
        "/work/physical/pro/05-pro-05-de3e0287.jpg",
        "/work/physical/pro/06-zoom-shirt.png",
        "/work/physical/pro/07-pro-07-9a95f687.jpg",
        "/work/physical/pro/08-pro-08-55c88388.png",
        "/work/physical/pro/09-pro-09-efa9fffd.jpg",
        "/work/physical/pro/10-pro-10-87a806ac.png",
        "/work/physical/pro/11-pro-11-a2880d77.jpg",
        "/work/physical/pro/12-pro-12-837cbdde.png",
        "/work/physical/pro/13-pro-13-62cff7a7.png",
        "/work/physical/pro/14-pro-14-1b40528b.jpg",
        "/work/physical/pro/15-pro-15-146fb7a1.png",
        "/work/physical/pro/16-pro-16-b71bead9.png",
        "/work/physical/pro/17-pro-17-60e44d64.png",
        "/work/physical/pro/18-pro-18-c48bbe25.png",
        "/work/physical/pro/19-pro-19-af10fe90.png",
      ],
    },
    {
      slug: "professional-production",
      title: "Professional Production",
      year: "2022",
      caption: "Local business promos",
      role: "Commercial Design",
      lane: "Production",
      featured: false,
      description:
        "Client-facing production including Presidential Touch Detailing — high-contrast promo for local service brands.",
      tags: ["Flyer", "Brand", "Production"],
      href: "/work/professional-production",
      adobe: "https://shonarip.myportfolio.com/professional-production",
      image: "/work/prez-wash.jpg",
    },
    {
      slug: "prints",
      title: "Prints",
      year: "2024",
      caption: "Personal prints",
      role: "Print Archive",
      lane: "Print",
      featured: false,
      description:
        "Solo print work — the still pieces that live off-screen.",
      tags: ["Print", "Archive"],
      href: "/work/prints",
      adobe: "https://shonarip.myportfolio.com/solo-work",
      image: "/work/manga2/Blue_Hues.jpg",
    },
  ],

  /** Homepage Prints — Adobe Prints carousel (Reach wires images; fans parked) */
  availablePrints: {
    heading: "Prints",
    intro:
      "Original pieces collected over time, all available as prints.",
    /** Adobe Prints solo-work — 17 stills, DZ carousel pack */
    images: [
      "/work/prints/carousel/01.jpg",
      "/work/prints/carousel/02.jpg",
      "/work/prints/carousel/03.jpg",
      "/work/prints/carousel/04.jpg",
      "/work/prints/carousel/05.jpg",
      "/work/prints/carousel/06.jpg",
      "/work/prints/carousel/07.jpg",
      "/work/prints/carousel/08.jpg",
      "/work/prints/carousel/09.jpg",
      "/work/prints/carousel/10.jpg",
      "/work/prints/carousel/11.jpg",
      "/work/prints/carousel/12.png",
      "/work/prints/carousel/13.jpg",
      "/work/prints/carousel/14.jpg",
      "/work/prints/carousel/15.jpg",
      "/work/prints/carousel/16.jpg",
      "/work/prints/carousel/17.jpg",
    ],
  },

  /**
   * All Works → Print lane archive (Chief lock 2026-09-18)
   * Order: Prints carousel 01–17, then Homage adobe 01–24,
   * then unique manga vault stills (manga.items + manga3 extras).
   * Coder: render like Photography rows + in-site lightbox; hide thin Prints project card from Print lane.
   */
  printArchive: {
    heading: "Print",
    intro:
      "Prints, Homage to Nihon, and manga pieces — still work made to live off the screen.",
    items: [
      {
        title: "Cyber Ranma",
        year: "2026",
        caption: "Static",
        series: "Homage to Nihon",
        image: "/work/homage/25-cyber-ranma.jpg",
        alt: "Anime girl with flowing iridescent hair and a chrome cybernetic arm, glowing gold against a pale sparkling haze.",
      },
      {
        title: "4 ur Eyez",
        year: "2026",
        caption: "Gaze",
        series: "Homage to Nihon",
        image: "/work/homage/26-4-ur-eyez.jpg",
        alt: "Extreme close-up of a manga eye in red and orange ink, a small figure reflected in its dark iris.",
      },
      {
        title: "Mei Mei",
        year: "2026",
        caption: "Cold",
        series: "Homage to Nihon",
        image: "/work/homage/27-mei-mei.jpg",
        alt: "Manga swordsman drifting through black starry space, cut by violet lightning and scattered teal petals.",
      },
      {
        title: "Contained",
        year: "2026",
        caption: "Held",
        series: "Homage to Nihon",
        image: "/work/homage/28-contained.jpg",
        alt: "Dark-haired man in a black coat sits in a white armchair holding a sword, framed by red and navy grunge.",
      },
      {
        title: "Cyan Bones",
        year: "2024",
        caption: "Print",
        series: "Prints",
        image: "/work/prints/carousel/01.jpg",
        alt: "Two cyan-lit skeletons lean into each other against a black field of smoky nebula color.",
      },
      {
        title: "Headphone Saint",
        year: "2024",
        caption: "Print",
        series: "Prints",
        image: "/work/prints/carousel/02.jpg",
        alt: "Golden skeleton in headphones sits beneath a blue halo, black wings spread against a hazy sunlit sky.",
      },
      {
        title: "New Beginnings",
        year: "2024",
        caption: "Print",
        series: "Prints",
        image: "/work/prints/carousel/03.jpg",
        alt: "Blue line-drawn skull over a Great Wave, white rings and Japanese text about endings and new beginnings on black.",
      },
      {
        title: "Hand in Orbit",
        year: "2024",
        caption: "Print",
        series: "Prints",
        image: "/work/prints/carousel/04.jpg",
        alt: "Gray hand wrapped in green vines and purple flowers floats inside black and white concentric rings.",
      },
      {
        title: "Censored Pier",
        year: "2024",
        caption: "Print",
        series: "Prints",
        image: "/work/prints/carousel/05.jpg",
        alt: "Woman in a teal top with red-painted arms and a black bar over her eyes, before a torn grayscale pier.",
      },
      {
        title: "Red Glove Bride",
        year: "2024",
        caption: "Print",
        series: "Prints",
        image: "/work/prints/carousel/06.jpg",
        alt: "Girl in a white dress and red gloves holds pale roses, streaked with red glitch and a distant pagoda.",
      },
      {
        title: "Pagoda Falls",
        year: "2024",
        caption: "Print",
        series: "Prints",
        image: "/work/prints/carousel/07.jpg",
        alt: "Pagoda on a dark cliff above a waterfall, set in a black starfield with pale moon circles.",
      },
      {
        title: "Floating City",
        year: "2024",
        caption: "Print",
        series: "Prints",
        image: "/work/prints/carousel/08.jpg",
        alt: "Neon-lit city block hovers in a deep starfield, a lone figure below in cold blue haze.",
      },
      {
        title: "Serpent Back",
        year: "2024",
        caption: "Print",
        series: "Prints",
        image: "/work/prints/carousel/09.jpg",
        alt: "Woman seen from behind, her back tattooed with a snake and washed in red light amid green smoke.",
      },
      {
        title: "Window Ink",
        year: "2024",
        caption: "Print",
        series: "Prints",
        image: "/work/prints/carousel/10.jpg",
        alt: "Black-and-white photo of a seated woman's tattooed back, a small bright window in the dark room.",
      },
      {
        title: "Knit Skyline",
        year: "2024",
        caption: "Print",
        series: "Prints",
        image: "/work/prints/carousel/11.jpg",
        alt: "Woman in a knit sweater looms over a sepia city skyline, cracked by white lightning and pale moons.",
      },
      {
        title: "Magenta Static",
        year: "2024",
        caption: "Print",
        series: "Prints",
        image: "/work/prints/carousel/12.png",
        alt: "Dense glitch collage of cracked textures and shadowy figures in magenta, green and black.",
      },
      {
        title: "Ascension",
        year: "2024",
        caption: "Print",
        series: "Prints",
        image: "/work/prints/carousel/13.jpg",
        alt: "Figure rises into cold blue light rays beneath chrome ASCENSION lettering.",
      },
      {
        title: "Neon Anatomy",
        year: "2024",
        caption: "Print",
        series: "Prints",
        image: "/work/prints/carousel/14.jpg",
        alt: "Muscular anatomical figure outlined in glowing red, green and blue, striding across dark navy.",
      },
      {
        title: "Skull Spectrum",
        year: "2024",
        caption: "Print",
        series: "Prints",
        image: "/work/prints/carousel/15.jpg",
        alt: "Grid of inked skulls tinted blue, violet, red, yellow, green and orange on a pastel gradient.",
      },
      {
        title: "Galaxy Torii",
        year: "2024",
        caption: "Print",
        series: "Prints",
        image: "/work/prints/carousel/16.jpg",
        alt: "Silhouette walks a bamboo path toward a torii gate under a purple and pink galaxy sky.",
      },
      {
        title: "Smoke Wings",
        year: "2024",
        caption: "Print",
        series: "Prints",
        image: "/work/prints/carousel/17.jpg",
        alt: "Ghostly white winged figures twist like smoke against amber sunset clouds.",
      },
      {
        title: "Held Close",
        year: "2024",
        caption: "Homage",
        series: "Homage to Nihon",
        image: "/work/homage/01.jpg",
        alt: "Manga girl with hair over one eye cradles a boy in her lap, inked in gold and blue amid swirling black.",
      },
      {
        title: "Flower Path",
        year: "2024",
        caption: "Homage",
        series: "Homage to Nihon",
        image: "/work/homage/02.png",
        alt: "Samurai with swords stands on a stone forest path framed by saturated red, blue and green foliage.",
      },
      {
        title: "Red Grin",
        year: "2024",
        caption: "Homage",
        series: "Homage to Nihon",
        image: "/work/homage/03.png",
        alt: "White-inked manga figure lies across a huge red grin, set in dark speckled space with faint kanji.",
      },
      {
        title: "Blue Scream",
        year: "2024",
        caption: "Homage",
        series: "Homage to Nihon",
        image: "/work/homage/04.png",
        alt: "White-haired figure with cracked skin crouches and screams, lit in electric blue on black.",
      },
      {
        title: "Violet Focus",
        year: "2024",
        caption: "Homage",
        series: "Homage to Nihon",
        image: "/work/homage/05.png",
        alt: "White-haired manga boy raises one hand, calm, beneath magenta and purple ink swirls.",
      },
      {
        title: "Storm Cry",
        year: "2024",
        caption: "Homage",
        series: "Homage to Nihon",
        image: "/work/homage/06.png",
        alt: "Spiky-haired manga face screams through blue lightning below a misty green forest.",
      },
      {
        title: "Coral Shards",
        year: "2024",
        caption: "Homage",
        series: "Homage to Nihon",
        image: "/work/homage/07.png",
        alt: "Coral-red and black fractured panels hold screaming manga faces and scratched texture.",
      },
      {
        title: "Blue Veil",
        year: "2024",
        caption: "Homage",
        series: "Homage to Nihon",
        image: "/work/homage/08.png",
        alt: "Long-haired manga swordsman in shadow, framed by icy blue trees, lightning and white bars.",
      },
      {
        title: "Blossom Warrior",
        year: "2024",
        caption: "Homage",
        series: "Homage to Nihon",
        image: "/work/homage/09.png",
        alt: "Warrior in a headband with a red-washed face glares through drifting cherry blossoms.",
      },
      {
        title: "Topknot Moon",
        year: "2024",
        caption: "Homage",
        series: "Homage to Nihon",
        image: "/work/homage/10.png",
        alt: "Man with a topknot in black stands among white moon rings, calligraphy and earthy textures.",
      },
      {
        title: "Heaven and Earth",
        year: "2024",
        caption: "Homage",
        series: "Homage to Nihon",
        image: "/work/homage/11.png",
        alt: "Violet energy burst collage with manga text reading through heaven and earth, on black.",
      },
      {
        title: "Ronin Gaze",
        year: "2024",
        caption: "Homage",
        series: "Homage to Nihon",
        image: "/work/homage/12.png",
        alt: "Close-up of a long-haired ronin's face in blue ink, beside brush calligraphy and white bars.",
      },
      {
        title: "Blue Cross",
        year: "2024",
        caption: "Homage",
        series: "Homage to Nihon",
        image: "/work/homage/13.png",
        alt: "Blue dotted face half-hidden behind a white cross, with kanji glyphs on starry black.",
      },
      {
        title: "Paper Ghost",
        year: "2024",
        caption: "Homage",
        series: "Homage to Nihon",
        image: "/work/homage/14.jpg",
        alt: "Head-and-shoulders silhouette filled with teal and red scribbles on crumpled paper and black brushstrokes.",
      },
      {
        title: "Marble Eyes",
        year: "2024",
        caption: "Homage",
        series: "Homage to Nihon",
        image: "/work/homage/15.jpg",
        alt: "A thin strip of eyes peeks out from a black-and-white marbled swirl.",
      },
      {
        title: "Ink Slit",
        year: "2024",
        caption: "Homage",
        series: "Homage to Nihon",
        image: "/work/homage/16.jpg",
        alt: "Wide black-and-white marbled swirl broken by a black strip where two eyes peer out.",
      },
      {
        title: "Marble Demon",
        year: "2024",
        caption: "Homage",
        series: "Homage to Nihon",
        image: "/work/homage/17.jpg",
        alt: "Horned black silhouette with white eyes rises from a black-and-white marbled swirl.",
      },
      {
        title: "Ink Ending",
        year: "2024",
        caption: "Homage",
        series: "Homage to Nihon",
        image: "/work/homage/18.jpg",
        alt: "Black-and-white marbling rings a dark void beside vertical Japanese text about endings and beginnings.",
      },
      {
        title: "Akira Petals",
        year: "2024",
        caption: "Homage",
        series: "Homage to Nihon",
        image: "/work/homage/19.jpg",
        alt: "Boy in a gray jacket stands among falling red petals on white, above red AKIRA lettering.",
      },
      {
        title: "Blue Wreckage",
        year: "2024",
        caption: "Homage",
        series: "Homage to Nihon",
        image: "/work/homage/20.png",
        alt: "Fragmented manga figure dissolves into a storm of blue and black watercolor.",
      },
      {
        title: "Moon Rose",
        year: "2024",
        caption: "Homage",
        series: "Homage to Nihon",
        image: "/work/homage/21.jpg",
        alt: "Pale manga girl with yellow eyes, wrapped in electric blue rose outlines beside a crescent moon.",
      },
      {
        title: "Ash Girl",
        year: "2024",
        caption: "Homage",
        series: "Homage to Nihon",
        image: "/work/homage/22.jpg",
        alt: "Long-haired manga girl with a red-smeared face kneels on dark ashen ground in grayscale.",
      },
      {
        title: "Cosmic Tunnel",
        year: "2024",
        caption: "Homage",
        series: "Homage to Nihon",
        image: "/work/homage/23.png",
        alt: "Manga girl in a cropped sweater and hair clip sits in a dark cosmic tunnel of violet light.",
      },
      {
        title: "Blue Crouch",
        year: "2024",
        caption: "Homage",
        series: "Homage to Nihon",
        image: "/work/homage/24.png",
        alt: "Spiky white-haired boy crouches in sneakers against splashes of deep blue and green.",
      },
      {
        title: "Connection",
        year: "2024",
        caption: "Charge",
        series: "Manga",
        image: "/work/manga2/Connection.jpg",
        alt: "Manga girl cradles a boy in her lap on dark rocks under a starry sky, with CONNECT lettering.",
      },
      {
        title: "Love Figures",
        year: "2024",
        caption: "Close",
        series: "Manga",
        image: "/work/manga2/Love_Figures.jpg",
        alt: "Red and black manga girls behind torn bars, with LOVE in ransom letters, SICKO and Japanese text.",
      },
      {
        title: "Two Face Girl",
        year: "2024",
        caption: "Split",
        series: "Manga",
        image: "/work/manga2/Two_facegirl.jpg",
        alt: "Horned girl with long black hair clutches her face behind a sliced eye strip, above red MONSTER text.",
      },
      {
        title: "Forever Lost",
        year: "2024",
        caption: "Longing",
        series: "Manga",
        image: "/work/manga2/Forever_lost.jpg",
        alt: "White-haired figure walks a starry gap between sketched city buildings, pale and lonely.",
      },
      {
        title: "Blue Hues",
        year: "2024",
        caption: "Cool",
        series: "Manga",
        image: "/work/manga2/Blue_Hues.jpg",
        alt: "Pale manga girl with yellow eyes framed by electric blue roses and a crescent moon on black.",
      },
      {
        title: "Kojiro",
        year: "2024",
        caption: "Kinetic",
        series: "Manga",
        image: "/work/manga2/Kojiro.jpg",
        alt: "Grayscale swordsman on a misty mountain ridge beside large brush kanji for bushido.",
      },
      {
        title: "Zoro",
        year: "2024",
        caption: "Grit",
        series: "Manga",
        image: "/work/manga2/zoro.jpg",
        alt: "Green-haired swordsman sits calmly in a kimono, haloed in green light with pink petals and Patience text.",
      },
      {
        title: "Soul of Japan",
        year: "2024",
        caption: "Quiet",
        series: "Manga",
        image: "/work/manga2/Soul_of_japan.jpg",
        alt: "Samurai in black robes stands with his sword before a typed Bushido quote on dark paper.",
      },
      {
        title: "Sicko",
        year: "2024",
        caption: "Dark",
        series: "Manga",
        image: "/work/manga2/Sicko.jpg",
        alt: "Horned girl with spiral white hair and a red-shaded face behind a black bar, over red SICKO text.",
      },
      {
        title: "Ronin",
        year: "2024",
        caption: "Alone",
        series: "Manga",
        image: "/work/manga2/Ronin.jpg",
        alt: "Grayscale procession of ghostly samurai marching down a narrow old town street, warped by a fisheye lens.",
      },
      {
        title: "2 Akira",
        year: "2024",
        caption: "Akira",
        series: "Manga",
        image: "/work/manga3/2_Akira.jpg",
        alt: "Boy in a gray jacket stands among falling red petals on white, above red AKIRA lettering.",
      },
      {
        title: "Ai",
        year: "2024",
        caption: "Ai",
        series: "Manga",
        image: "/work/manga3/Ai.jpg",
        alt: "Halftone close-up of an open pink mouth and tongue beside a black-and-white circle and red kanji.",
      },
      {
        title: "Equal Sides",
        year: "2024",
        caption: "Balance",
        series: "Manga",
        image: "/work/manga3/Equal_Sides.jpg",
        alt: "Gray hand wrapped in green vines and purple flowers floats inside black and white concentric rings.",
      },
      {
        title: "Fire Force",
        year: "2024",
        caption: "Heat",
        series: "Manga",
        image: "/work/manga3/Fire_Force.jpg",
        alt: "Manga youth in blue overalls before a red flame ring, under red LATOM and Fire Force lettering.",
      },
      {
        title: "Hebi",
        year: "2024",
        caption: "Coil",
        series: "Manga",
        image: "/work/manga3/Hebi.jpg",
        alt: "Horned manga girl with red skin and a snake tattoo smiles shyly among pink blossoms and a coiled serpent.",
      },
      {
        title: "Kagurabachi",
        year: "2024",
        caption: "Blade",
        series: "Manga",
        image: "/work/manga3/Kagurabachi.jpg",
        alt: "Dark-clad manga swordsman slashes through an explosion of cyan, orange and black ink.",
      },
      {
        title: "Lover",
        year: "2024",
        caption: "Soft",
        series: "Manga",
        image: "/work/manga3/Lover.jpg",
        alt: "Pink-washed profile of a horned girl with closed eyes, a star on her cheek and a black choker.",
      },
      {
        title: "Mirage",
        year: "2024",
        caption: "Mirage",
        series: "Manga",
        image: "/work/manga3/Mirage0.jpg",
        alt: "Glowing vertical column of manga text floats in a storm of black-and-white brushed streaks.",
      },
      {
        title: "Momose",
        year: "2024",
        caption: "Quiet",
        series: "Manga",
        image: "/work/manga3/Momose.png",
        alt: "Pastel manga girl with a blue flower in her hair wears a floral kimono against blurred neon city light.",
      },
      {
        title: "Shibuya Experiment",
        year: "2024",
        caption: "City",
        series: "Manga",
        image: "/work/manga3/Shibuya_Experiment.png",
        alt: "Shadowed face in red light over a dark city skyline, above a white brush kanji and the word death.",
      },
      {
        title: "Sicko Girl",
        year: "2024",
        caption: "Dark",
        series: "Manga",
        image: "/work/manga3/Sicko_Girl.png",
        alt: "Pink-haired manga girl in twin tails crouches forward grinning, over glowing red SICKO text.",
      },
      {
        title: "Smoker",
        year: "2024",
        caption: "Smoke",
        series: "Manga",
        image: "/work/manga3/Smoker.jpg",
        alt: "Long-haired manga figure with a cigarette, orange and black hair, beside mint green circles on white.",
      },
      {
        title: "Space Girl",
        year: "2024",
        caption: "Void",
        series: "Manga",
        image: "/work/manga3/Space_Girl.jpg",
        alt: "Long-haired girl in a galaxy-print dress with a censor bar over her eyes, among floating planets.",
      },
      {
        title: "Tanjiro",
        year: "2024",
        caption: "Fire",
        series: "Manga",
        image: "/work/manga3/Tanjiro.jpg",
        alt: "Split manga boy raising a flaming sword, framed by black bars and red fire circles on white.",
      },
      {
        title: "Vagabondz",
        year: "2024",
        caption: "Wander",
        series: "Manga",
        image: "/work/manga3/Vagabondz.jpg",
        alt: "Blindfolded swordsman in harsh black-and-white grain beside Think only of your art and Bushido text.",
      },
      {
        title: "Lust",
        year: "2024",
        caption: "Desire",
        series: "Manga",
        image: "/work/manga3/lust.jpg",
        alt: "Horned girl in red wash with a black bar across her eyes, above bold red LUST lettering.",
      },
    ],
  },

  /**
   * All Works → Manga lane archive (Chief lock 2026-09-18)
   * Order: Homage adobe 01–24, then unique manga vault (manga.items + manga3 extras),
   * then unique /work/deck/ fills. No Prints.
   * Coder: render like Photography/Print rows + in-site lightbox; hide thin Manga/Homage project card clutter in Manga lane.
   */
  mangaArchive: {
    heading: "Manga",
    intro:
      "Manga and anime pieces — Homage to Nihon edits and personal work, one mood at a time.",
    items: [
      {
        title: "Held Close",
        year: "2024",
        caption: "Homage",
        series: "Homage to Nihon",
        image: "/work/homage/01.jpg",
        alt: "Manga girl with hair over one eye cradles a boy in her lap, inked in gold and blue amid swirling black.",
      },
      {
        title: "Flower Path",
        year: "2024",
        caption: "Homage",
        series: "Homage to Nihon",
        image: "/work/homage/02.png",
        alt: "Samurai with swords stands on a stone forest path framed by saturated red, blue and green foliage.",
      },
      {
        title: "Red Grin",
        year: "2024",
        caption: "Homage",
        series: "Homage to Nihon",
        image: "/work/homage/03.png",
        alt: "White-inked manga figure lies across a huge red grin, set in dark speckled space with faint kanji.",
      },
      {
        title: "Blue Scream",
        year: "2024",
        caption: "Homage",
        series: "Homage to Nihon",
        image: "/work/homage/04.png",
        alt: "White-haired figure with cracked skin crouches and screams, lit in electric blue on black.",
      },
      {
        title: "Violet Focus",
        year: "2024",
        caption: "Homage",
        series: "Homage to Nihon",
        image: "/work/homage/05.png",
        alt: "White-haired manga boy raises one hand, calm, beneath magenta and purple ink swirls.",
      },
      {
        title: "Storm Cry",
        year: "2024",
        caption: "Homage",
        series: "Homage to Nihon",
        image: "/work/homage/06.png",
        alt: "Spiky-haired manga face screams through blue lightning below a misty green forest.",
      },
      {
        title: "Coral Shards",
        year: "2024",
        caption: "Homage",
        series: "Homage to Nihon",
        image: "/work/homage/07.png",
        alt: "Coral-red and black fractured panels hold screaming manga faces and scratched texture.",
      },
      {
        title: "Blue Veil",
        year: "2024",
        caption: "Homage",
        series: "Homage to Nihon",
        image: "/work/homage/08.png",
        alt: "Long-haired manga swordsman in shadow, framed by icy blue trees, lightning and white bars.",
      },
      {
        title: "Blossom Warrior",
        year: "2024",
        caption: "Homage",
        series: "Homage to Nihon",
        image: "/work/homage/09.png",
        alt: "Warrior in a headband with a red-washed face glares through drifting cherry blossoms.",
      },
      {
        title: "Topknot Moon",
        year: "2024",
        caption: "Homage",
        series: "Homage to Nihon",
        image: "/work/homage/10.png",
        alt: "Man with a topknot in black stands among white moon rings, calligraphy and earthy textures.",
      },
      {
        title: "Heaven and Earth",
        year: "2024",
        caption: "Homage",
        series: "Homage to Nihon",
        image: "/work/homage/11.png",
        alt: "Violet energy burst collage with manga text reading through heaven and earth, on black.",
      },
      {
        title: "Ronin Gaze",
        year: "2024",
        caption: "Homage",
        series: "Homage to Nihon",
        image: "/work/homage/12.png",
        alt: "Close-up of a long-haired ronin's face in blue ink, beside brush calligraphy and white bars.",
      },
      {
        title: "Blue Cross",
        year: "2024",
        caption: "Homage",
        series: "Homage to Nihon",
        image: "/work/homage/13.png",
        alt: "Blue dotted face half-hidden behind a white cross, with kanji glyphs on starry black.",
      },
      {
        title: "Paper Ghost",
        year: "2024",
        caption: "Homage",
        series: "Homage to Nihon",
        image: "/work/homage/14.jpg",
        alt: "Head-and-shoulders silhouette filled with teal and red scribbles on crumpled paper and black brushstrokes.",
      },
      {
        title: "Marble Eyes",
        year: "2024",
        caption: "Homage",
        series: "Homage to Nihon",
        image: "/work/homage/15.jpg",
        alt: "A thin strip of eyes peeks out from a black-and-white marbled swirl.",
      },
      {
        title: "Ink Slit",
        year: "2024",
        caption: "Homage",
        series: "Homage to Nihon",
        image: "/work/homage/16.jpg",
        alt: "Wide black-and-white marbled swirl broken by a black strip where two eyes peer out.",
      },
      {
        title: "Marble Demon",
        year: "2024",
        caption: "Homage",
        series: "Homage to Nihon",
        image: "/work/homage/17.jpg",
        alt: "Horned black silhouette with white eyes rises from a black-and-white marbled swirl.",
      },
      {
        title: "Ink Ending",
        year: "2024",
        caption: "Homage",
        series: "Homage to Nihon",
        image: "/work/homage/18.jpg",
        alt: "Black-and-white marbling rings a dark void beside vertical Japanese text about endings and beginnings.",
      },
      {
        title: "Akira Petals",
        year: "2024",
        caption: "Homage",
        series: "Homage to Nihon",
        image: "/work/homage/19.jpg",
        alt: "Boy in a gray jacket stands among falling red petals on white, above red AKIRA lettering.",
      },
      {
        title: "Blue Wreckage",
        year: "2024",
        caption: "Homage",
        series: "Homage to Nihon",
        image: "/work/homage/20.png",
        alt: "Fragmented manga figure dissolves into a storm of blue and black watercolor.",
      },
      {
        title: "Moon Rose",
        year: "2024",
        caption: "Homage",
        series: "Homage to Nihon",
        image: "/work/homage/21.jpg",
        alt: "Pale manga girl with yellow eyes, wrapped in electric blue rose outlines beside a crescent moon.",
      },
      {
        title: "Ash Girl",
        year: "2024",
        caption: "Homage",
        series: "Homage to Nihon",
        image: "/work/homage/22.jpg",
        alt: "Long-haired manga girl with a red-smeared face kneels on dark ashen ground in grayscale.",
      },
      {
        title: "Cosmic Tunnel",
        year: "2024",
        caption: "Homage",
        series: "Homage to Nihon",
        image: "/work/homage/23.png",
        alt: "Manga girl in a cropped sweater and hair clip sits in a dark cosmic tunnel of violet light.",
      },
      {
        title: "Blue Crouch",
        year: "2024",
        caption: "Homage",
        series: "Homage to Nihon",
        image: "/work/homage/24.png",
        alt: "Spiky white-haired boy crouches in sneakers against splashes of deep blue and green.",
      },
      {
        title: "Connection",
        year: "2024",
        caption: "Charge",
        series: "Manga",
        image: "/work/manga2/Connection.jpg",
        alt: "Manga girl cradles a boy in her lap on dark rocks under a starry sky, with CONNECT lettering.",
      },
      {
        title: "Love Figures",
        year: "2024",
        caption: "Close",
        series: "Manga",
        image: "/work/manga2/Love_Figures.jpg",
        alt: "Red and black manga girls behind torn bars, with LOVE in ransom letters, SICKO and Japanese text.",
      },
      {
        title: "Two Face Girl",
        year: "2024",
        caption: "Split",
        series: "Manga",
        image: "/work/manga2/Two_facegirl.jpg",
        alt: "Horned girl with long black hair clutches her face behind a sliced eye strip, above red MONSTER text.",
      },
      {
        title: "Forever Lost",
        year: "2024",
        caption: "Longing",
        series: "Manga",
        image: "/work/manga2/Forever_lost.jpg",
        alt: "White-haired figure walks a starry gap between sketched city buildings, pale and lonely.",
      },
      {
        title: "Blue Hues",
        year: "2024",
        caption: "Cool",
        series: "Manga",
        image: "/work/manga2/Blue_Hues.jpg",
        alt: "Pale manga girl with yellow eyes framed by electric blue roses and a crescent moon on black.",
      },
      {
        title: "Kojiro",
        year: "2024",
        caption: "Kinetic",
        series: "Manga",
        image: "/work/manga2/Kojiro.jpg",
        alt: "Grayscale swordsman on a misty mountain ridge beside large brush kanji for bushido.",
      },
      {
        title: "Zoro",
        year: "2024",
        caption: "Grit",
        series: "Manga",
        image: "/work/manga2/zoro.jpg",
        alt: "Green-haired swordsman sits calmly in a kimono, haloed in green light with pink petals and Patience text.",
      },
      {
        title: "Soul of Japan",
        year: "2024",
        caption: "Quiet",
        series: "Manga",
        image: "/work/manga2/Soul_of_japan.jpg",
        alt: "Samurai in black robes stands with his sword before a typed Bushido quote on dark paper.",
      },
      {
        title: "Sicko",
        year: "2024",
        caption: "Dark",
        series: "Manga",
        image: "/work/manga2/Sicko.jpg",
        alt: "Horned girl with spiral white hair and a red-shaded face behind a black bar, over red SICKO text.",
      },
      {
        title: "Ronin",
        year: "2024",
        caption: "Alone",
        series: "Manga",
        image: "/work/manga2/Ronin.jpg",
        alt: "Grayscale procession of ghostly samurai marching down a narrow old town street, warped by a fisheye lens.",
      },
      {
        title: "2 Akira",
        year: "2024",
        caption: "Akira",
        series: "Manga",
        image: "/work/manga3/2_Akira.jpg",
        alt: "Boy in a gray jacket stands among falling red petals on white, above red AKIRA lettering.",
      },
      {
        title: "Ai",
        year: "2024",
        caption: "Ai",
        series: "Manga",
        image: "/work/manga3/Ai.jpg",
        alt: "Halftone close-up of an open pink mouth and tongue beside a black-and-white circle and red kanji.",
      },
      {
        title: "Equal Sides",
        year: "2024",
        caption: "Balance",
        series: "Manga",
        image: "/work/manga3/Equal_Sides.jpg",
        alt: "Gray hand wrapped in green vines and purple flowers floats inside black and white concentric rings.",
      },
      {
        title: "Fire Force",
        year: "2024",
        caption: "Heat",
        series: "Manga",
        image: "/work/manga3/Fire_Force.jpg",
        alt: "Manga youth in blue overalls before a red flame ring, under red LATOM and Fire Force lettering.",
      },
      {
        title: "Hebi",
        year: "2024",
        caption: "Coil",
        series: "Manga",
        image: "/work/manga3/Hebi.jpg",
        alt: "Horned manga girl with red skin and a snake tattoo smiles shyly among pink blossoms and a coiled serpent.",
      },
      {
        title: "Kagurabachi",
        year: "2024",
        caption: "Blade",
        series: "Manga",
        image: "/work/manga3/Kagurabachi.jpg",
        alt: "Dark-clad manga swordsman slashes through an explosion of cyan, orange and black ink.",
      },
      {
        title: "Lover",
        year: "2024",
        caption: "Soft",
        series: "Manga",
        image: "/work/manga3/Lover.jpg",
        alt: "Pink-washed profile of a horned girl with closed eyes, a star on her cheek and a black choker.",
      },
      {
        title: "Mirage",
        year: "2024",
        caption: "Mirage",
        series: "Manga",
        image: "/work/manga3/Mirage0.jpg",
        alt: "Glowing vertical column of manga text floats in a storm of black-and-white brushed streaks.",
      },
      {
        title: "Momose",
        year: "2024",
        caption: "Quiet",
        series: "Manga",
        image: "/work/manga3/Momose.png",
        alt: "Pastel manga girl with a blue flower in her hair wears a floral kimono against blurred neon city light.",
      },
      {
        title: "Shibuya Experiment",
        year: "2024",
        caption: "City",
        series: "Manga",
        image: "/work/manga3/Shibuya_Experiment.png",
        alt: "Shadowed face in red light over a dark city skyline, above a white brush kanji and the word death.",
      },
      {
        title: "Sicko Girl",
        year: "2024",
        caption: "Dark",
        series: "Manga",
        image: "/work/manga3/Sicko_Girl.png",
        alt: "Pink-haired manga girl in twin tails crouches forward grinning, over glowing red SICKO text.",
      },
      {
        title: "Smoker",
        year: "2024",
        caption: "Smoke",
        series: "Manga",
        image: "/work/manga3/Smoker.jpg",
        alt: "Long-haired manga figure with a cigarette, orange and black hair, beside mint green circles on white.",
      },
      {
        title: "Space Girl",
        year: "2024",
        caption: "Void",
        series: "Manga",
        image: "/work/manga3/Space_Girl.jpg",
        alt: "Long-haired girl in a galaxy-print dress with a censor bar over her eyes, among floating planets.",
      },
      {
        title: "Tanjiro",
        year: "2024",
        caption: "Fire",
        series: "Manga",
        image: "/work/manga3/Tanjiro.jpg",
        alt: "Split manga boy raising a flaming sword, framed by black bars and red fire circles on white.",
      },
      {
        title: "Vagabondz",
        year: "2024",
        caption: "Wander",
        series: "Manga",
        image: "/work/manga3/Vagabondz.jpg",
        alt: "Blindfolded swordsman in harsh black-and-white grain beside Think only of your art and Bushido text.",
      },
      {
        title: "Lust",
        year: "2024",
        caption: "Desire",
        series: "Manga",
        image: "/work/manga3/lust.jpg",
        alt: "Horned girl in red wash with a black bar across her eyes, above bold red LUST lettering.",
      },
      {
        title: "Alone Together",
        year: "2024",
        caption: "Deck",
        series: "Deck",
        image: "/work/deck/alone-together.jpg",
        alt: "Blonde manga girl in a sundress holds a navy umbrella in the rain beside stacked red TOGETHER text.",
      },
      {
        title: "Ascension",
        year: "2024",
        caption: "Deck",
        series: "Deck",
        image: "/work/deck/ascension.jpg",
        alt: "Figure rises into cold blue light rays beneath chrome ASCENSION lettering.",
      },
      {
        title: "Bankai",
        year: "2024",
        caption: "Deck",
        series: "Deck",
        image: "/work/deck/bankai.jpg",
        alt: "Gray manga face with a wide toothy grin and fierce slit eyes, cracked down one side, on black.",
      },
      {
        title: "Black Flash",
        year: "2024",
        caption: "Deck",
        series: "Deck",
        image: "/work/deck/black-flash.png",
        alt: "Blood-red splintered figure in a dark triangle, drifting black shards overhead.",
      },
      {
        title: "Blucano",
        year: "2024",
        caption: "Deck",
        series: "Deck",
        image: "/work/deck/blucano.jpg",
        alt: "Volcano silhouetted under a violet dusk sky, smoke plume above and glowing blue-white lava below.",
      },
      {
        title: "Bushido",
        year: "2024",
        caption: "Deck",
        series: "Deck",
        image: "/work/deck/bushido01.jpg",
        alt: "Black-and-white marbling rings a dark void beside vertical Japanese text about endings and beginnings.",
      },
      {
        title: "Call of the Night",
        year: "2024",
        caption: "Deck",
        series: "Deck",
        image: "/work/deck/call-of-the-night.jpg",
        alt: "Woman in a knit sweater looms over a sepia city skyline, cracked by white lightning and pale moons.",
      },
      {
        title: "City on Fire",
        year: "2024",
        caption: "Deck",
        series: "Deck",
        image: "/work/deck/city-on-fire.jpg",
        alt: "Headless armored figure rendered in glitching neon pixels, standing against dark cracked texture.",
      },
      {
        title: "Conflicted",
        year: "2024",
        caption: "Deck",
        series: "Deck",
        image: "/work/deck/conflicted.jpg",
        alt: "Muscular anatomical figure outlined in glowing red, green and blue, striding across dark navy.",
      },
      {
        title: "Contemplation",
        year: "2024",
        caption: "Deck",
        series: "Deck",
        image: "/work/deck/contemplation.jpg",
        alt: "Brooding dark-haired manga figure over a red glowing field with a cyan ring and a pale moon.",
      },
      {
        title: "Cosmic",
        year: "2024",
        caption: "Deck",
        series: "Deck",
        image: "/work/deck/cosmic.jpg",
        alt: "Pagoda on a dark cliff above a waterfall, set in a black starfield with pale moon circles.",
      },
      {
        title: "Cry While You Can",
        year: "2024",
        caption: "Deck",
        series: "Deck",
        image: "/work/deck/cry-while.jpg",
        alt: "Manga girl with a cigarette and a torn-photo tearful eye, over ransom-letter Cry While You Can text.",
      },
      {
        title: "Dabi",
        year: "2024",
        caption: "Deck",
        series: "Deck",
        image: "/work/deck/dabi.jpg",
        alt: "Spiky-haired manga figure thrusts an open hand forward, a black bar across his eyes and blue flame below.",
      },
      {
        title: "Dead Eyes",
        year: "2024",
        caption: "Deck",
        series: "Deck",
        image: "/work/deck/dead-eyes.jpg",
        alt: "Pink-washed manga girl's face with one eye inside a black circle, a horn above and red SICKO text.",
      },
      {
        title: "Devil Inside",
        year: "2024",
        caption: "Deck",
        series: "Deck",
        image: "/work/deck/devil-inside.jpg",
        alt: "Manga girl in red sits in a paneled room behind a torn strip, with ransom-letter Devil Inside text.",
      },
      {
        title: "Dream Girl",
        year: "2024",
        caption: "Deck",
        series: "Deck",
        image: "/work/deck/dream-girl.png",
        alt: "Dark collage of a manga figure with calligraphy, gray rings and Die With Memories Not Dreams text.",
      },
      {
        title: "Duality Icarus",
        year: "2024",
        caption: "Deck",
        series: "Deck",
        image: "/work/manga/deck/duality-icarus.jpg",
        alt: "Crouching pale figure over red splashes on black, beneath a white brush kanji and the word death.",
      },
      {
        title: "Fermenting",
        year: "2024",
        caption: "Deck",
        series: "Deck",
        image: "/work/deck/fermenting.jpg",
        alt: "Head-and-shoulders silhouette filled with teal and red scribbles on crumpled paper and black brushstrokes.",
      },
      {
        title: "First Issue Nue",
        year: "2024",
        caption: "Deck",
        series: "Deck",
        image: "/work/deck/first-issue-nue.jpg",
        alt: "Magenta and violet sketched portrait of a long-haired woman under Live Long And Do Dope Shit text.",
      },
      {
        title: "Geto",
        year: "2024",
        caption: "Deck",
        series: "Deck",
        image: "/work/deck/geto.png",
        alt: "Man with a topknot in black stands among white moon rings, calligraphy and earthy textures.",
      },
      {
        title: "Gojo",
        year: "2024",
        caption: "Deck",
        series: "Deck",
        image: "/work/deck/gojo.png",
        alt: "Blood-streaked manga face with glowing blue eyes behind a raised hand crackling with blue light.",
      },
      {
        title: "HxH",
        year: "2024",
        caption: "Deck",
        series: "Deck",
        image: "/work/manga/deck/hxh.jpg",
        alt: "Spiky white-haired boy crouches in sneakers against splashes of deep blue and green.",
      },
      {
        title: "Karumi",
        year: "2024",
        caption: "Deck",
        series: "Deck",
        image: "/work/manga/deck/karumi.jpg",
        alt: "Long-haired manga girl in black lingerie on a red Japanese magazine-cover layout with a CERTIFIED stamp.",
      },
      {
        title: "Minami",
        year: "2024",
        caption: "Deck",
        series: "Deck",
        image: "/work/deck/minami.png",
        alt: "Coral-red and black fractured panels hold screaming manga faces and scratched texture.",
      },
      {
        title: "Misa",
        year: "2024",
        caption: "Deck",
        series: "Deck",
        image: "/work/deck/misa.png",
        alt: "Gothic manga girl with orange twin tails, a black choker and a cross necklace on dark grain.",
      },
      {
        title: "Moments Between",
        year: "2024",
        caption: "Deck",
        series: "Deck",
        image: "/work/deck/moments-between.png",
        alt: "Dark-haired manga girl in a bow blouse over red and green haze, with a big 4 and Live Long text.",
      },
      {
        title: "Night Mania",
        year: "2024",
        caption: "Deck",
        series: "Deck",
        image: "/work/deck/night-mania.png",
        alt: "Dense glitch collage of cracked textures and shadowy figures in magenta, green and black.",
      },
      {
        title: "Opposites",
        year: "2024",
        caption: "Deck",
        series: "Deck",
        image: "/work/deck/opposites.jpg",
        alt: "A thin strip of eyes peeks out from a black-and-white marbled swirl.",
      },
      {
        title: "Post Mortem Boredom",
        year: "2024",
        caption: "Deck",
        series: "Deck",
        image: "/work/deck/post-mortem-boredom.jpg",
        alt: "Manga girl with hair over one eye cradles a boy in her lap, inked in gold and blue amid swirling black.",
      },
      {
        title: "Red Ona",
        year: "2024",
        caption: "Deck",
        series: "Deck",
        image: "/work/deck/red-ona.png",
        alt: "Long-haired manga girl in black lingerie before a red neon crescent moon and Japanese cover text.",
      },
      {
        title: "Reze",
        year: "2024",
        caption: "Deck",
        series: "Deck",
        image: "/work/deck/reze.png",
        alt: "Dark-haired manga figure in deep blue with white feathers and a speech bubble reading My name's Reze.",
      },
      {
        title: "Solitude",
        year: "2024",
        caption: "Deck",
        series: "Deck",
        image: "/work/deck/solitude.png",
        alt: "Tiny red-lit figure sits alone in a dark rippling pool under a black, starless sky.",
      },
      {
        title: "Starry Nights",
        year: "2024",
        caption: "Deck",
        series: "Deck",
        image: "/work/deck/starry-nights.png",
        alt: "Manga girl in a cropped sweater and hair clip sits in a dark cosmic tunnel of violet light.",
      },
      {
        title: "The Blade",
        year: "2024",
        caption: "Deck",
        series: "Deck",
        image: "/work/deck/the-blade.jpg",
        alt: "Single white-edged curved blade cuts diagonally across solid black.",
      },
      {
        title: "Till Death",
        year: "2024",
        caption: "Deck",
        series: "Deck",
        image: "/work/deck/till-death.jpg",
        alt: "Girl in a white dress and red gloves holds pale roses, streaked with red glitch and a distant pagoda.",
      },
      {
        title: "Torso",
        year: "2024",
        caption: "Deck",
        series: "Deck",
        image: "/work/deck/torso.jpg",
        alt: "Nude manga torso washed in red with green floral tattoos and white cloth at the hips, planets beside.",
      },
      {
        title: "True Mask",
        year: "2024",
        caption: "Deck",
        series: "Deck",
        image: "/work/deck/true-mask.jpg",
        alt: "Cracked porcelain-like manga face with dark hair, dotted with blue bird icons on white.",
      },
      {
        title: "Wonder Girl",
        year: "2024",
        caption: "Deck",
        series: "Deck",
        image: "/work/deck/wonder-girl.png",
        alt: "Manga figure in a face mask dissolves into swirling red, green and black paint, with bold white rings.",
      },
      {
        title: "Yume",
        year: "2024",
        caption: "Deck",
        series: "Deck",
        image: "/work/deck/yume.jpg",
        alt: "Dense neon contour lines in red, green and blue trace a hidden figure across black.",
      },
    ],
  },

  /**
   * All Works → Production lane archive (Chief lock 2026-09-18)
   * Adobe Professional Production order — 19 stills under /work/physical/pro/.
   * No tees (those stay on Physical Featured/case). Lightbox like Photo/Print/Manga.
   * Coder: hide thin Professional Production project card in Production lane.
   */
  productionArchive: {
    heading: "Production",
    intro:
      "Professional production — flyers, business cards, signage, and brand pieces for real clients.",
    items: [
      {
        title: "Kylen Granson Books",
        year: "2024",
        caption: "Pro",
        series: "Professional Production",
        image: "/work/physical/pro/01-kylen-granson-books.png",
        alt: "Blue Colts-style flyer: Kylen Granson in a No. 83 jersey asks fans to donate books for Indiana students.",
      },
      {
        title: "Presidential Touch Limo",
        year: "2024",
        caption: "Pro",
        series: "Professional Production",
        image: "/work/physical/pro/02-presidential-touch-limo.jpg",
        alt: "Presidential Touch limo flyer with a black stretch limousine under an American flag over a night city.",
      },
      {
        title: "Smackem Gooz Menu",
        year: "2024",
        caption: "Pro",
        series: "Professional Production",
        image: "/work/physical/pro/03-smackem-gooz-menu.jpg",
        alt: "Purple and gold Smack'em Gooz Kitchen We Cater menu listing daily dinners, desserts and drinks.",
      },
      {
        title: "Vixen Palace Flyer",
        year: "2024",
        caption: "Pro",
        series: "Professional Production",
        image: "/work/physical/pro/04-pro-04-d7dbf12d.jpg",
        alt: "Black and gold Thee Vixen Palace flyer with a glowing castle logo and bold Book Now banner.",
      },
      {
        title: "Take Point Cards",
        year: "2024",
        caption: "Pro",
        series: "Professional Production",
        image: "/work/physical/pro/05-pro-05-de3e0287.jpg",
        alt: "Pair of black business cards for Take Point Protective Services with a gold phoenix shield logo.",
      },
      {
        title: "Zoom Shirt",
        year: "2024",
        caption: "Pro",
        series: "Professional Production",
        image: "/work/physical/pro/06-zoom-shirt.png",
        alt: "Front and back business cards for Powa Tiling Decor in white and beige, with tile photos and contacts.",
      },
      {
        title: "Presidential Detailing Cards",
        year: "2024",
        caption: "Pro",
        series: "Professional Production",
        image: "/work/physical/pro/07-pro-07-9a95f687.jpg",
        alt: "Two Presidential Touch Detailing business cards with an American flag, a dark SUV and sparkles.",
      },
      {
        title: "After Dark Audio",
        year: "2024",
        caption: "Pro",
        series: "Professional Production",
        image: "/work/physical/pro/08-pro-08-55c88388.png",
        alt: "Black and neon green After Dark Car Audio and Security cards with a sports car and speakers.",
      },
      {
        title: "Laundry Kleen Cards",
        year: "2024",
        caption: "Pro",
        series: "Professional Production",
        image: "/work/physical/pro/09-pro-09-efa9fffd.jpg",
        alt: "Two black sparkle business cards for Laundry Kleen, lettered in silver and teal.",
      },
      {
        title: "Sweet Creationz Cards",
        year: "2024",
        caption: "Pro",
        series: "Professional Production",
        image: "/work/physical/pro/10-pro-10-87a806ac.png",
        alt: "Black business cards for Sweet Creationz and More with candy, ice cream and neon pink lettering.",
      },
      {
        title: "Mr. Parker Cleaning",
        year: "2024",
        caption: "Pro",
        series: "Professional Production",
        image: "/work/physical/pro/11-pro-11-a2880d77.jpg",
        alt: "Bright blue bubble-themed business cards for Mr. Parker Cleaning Service with a smiling couple.",
      },
      {
        title: "Royal Lioness Staging",
        year: "2024",
        caption: "Pro",
        series: "Professional Production",
        image: "/work/physical/pro/12-pro-12-837cbdde.png",
        alt: "Pink and white Royal Lioness Staging business cards with a castle crest and a lavender room.",
      },
      {
        title: "Boss Eggs Banner",
        year: "2024",
        caption: "Pro",
        series: "Professional Production",
        image: "/work/physical/pro/13-pro-13-62cff7a7.png",
        alt: "Hot pink Boss Eggs retractable banner showing jars of pickled eggs, bowls of food and hours.",
      },
      {
        title: "1st Class Insurance",
        year: "2024",
        caption: "Pro",
        series: "Professional Production",
        image: "/work/physical/pro/14-pro-14-1b40528b.jpg",
        alt: "Two sky-blue 1st Class Insurance roll-up banners with a jet, advertising affordable health and life plans.",
      },
      {
        title: "Roadway Ready",
        year: "2024",
        caption: "Pro",
        series: "Professional Production",
        image: "/work/physical/pro/15-pro-15-146fb7a1.png",
        alt: "White distressed serif R monogram centered on a black square.",
      },
      {
        title: "Masons",
        year: "2024",
        caption: "Pro",
        series: "Professional Production",
        image: "/work/physical/pro/16-pro-16-b71bead9.png",
        alt: "Blue and gold Free and Accepted Masons emblem with the square, compass and G.",
      },
      {
        title: "The Shore",
        year: "2024",
        caption: "Pro",
        series: "Professional Production",
        image: "/work/physical/pro/17-pro-17-60e44d64.png",
        alt: "Teal circular logo for The Shore Lakefront at Keystone with crossed paddles and sport balls.",
      },
      {
        title: "Food Bus Logo",
        year: "2024",
        caption: "Pro",
        series: "Professional Production",
        image: "/work/physical/pro/18-pro-18-c48bbe25.png",
        alt: "Deep purple food-truck logo shaped like a steaming cloche, reading Chef TLC The Food Bus in pink.",
      },
      {
        title: "Farm Aid 2023",
        year: "2024",
        caption: "Pro",
        series: "Professional Production",
        image: "/work/physical/pro/19-pro-19-af10fe90.png",
        alt: "Farm Aid 2023 poster in green and sky blue, with sprouting plants rising from an Indiana state outline.",
      },
    ],
  },

  /** Manga chapter — fan decks (manga + Adobe Prints) + lightbox; not equal-weight case studies */
  manga: {
    heading: "Manga",
    intro:
      "Homage edits and personal pieces — one-word moods, night palette, essence over copy.",
    /** Chief: homepage shows only these 6; rest via See all homage / lightbox */
    homepageCurated: [
      "Sicko",
      "Soul of Japan",
      "Ronin",
      "Forever Lost",
      "Connection",
      "Blue Hues",
    ],
    items: [
      {
        title: "Connection",
        year: "2024",
        caption: "Charge",
        image: "/work/manga2/Connection.jpg",
        alt: "Manga girl in an ochre hooded coat sits above a sleeping figure in a blue hood on dark rocks under a starry blue sky, with the word CONNECT across the middle.",
      },
      {
        title: "Love Figures",
        year: "2024",
        caption: "Close",
        image: "/work/manga2/Love_Figures.jpg",
        alt: "Collage of three red-faced manga women with black bars over their eyes on torn paper and Japanese text, with cut-out letters spelling LOVE.",
      },
      {
        title: "Two Face Girl",
        year: "2024",
        caption: "Split",
        image: "/work/manga2/Two_facegirl.jpg",
        alt: "Horned manga girl in red, her face sliced into shifted horizontal bands and her hands on her cheeks, with the word MONSTER at the bottom.",
      },
      {
        title: "Forever Lost",
        year: "2024",
        caption: "Longing",
        image: "/work/manga2/Forever_lost.jpg",
        alt: "Pale manga figure walking down a narrow strip of starry night sky between two panels of washed-out industrial rooftops.",
      },
      {
        title: "Blue Hues",
        year: "2024",
        caption: "Cool",
        image: "/work/manga2/Blue_Hues.jpg",
        alt: "Close-up manga portrait with glowing yellow eyes and blue roses in her hair, tinted blue and violet beside a crescent moon.",
      },
      {
        title: "Kojiro",
        year: "2024",
        caption: "Kinetic",
        image: "/work/manga2/Kojiro.jpg",
        alt: "Black-and-white sketch-textured samurai with flowing hair on a mountainside, with the kanji for bushido in heavy black strokes at left.",
      },
      {
        title: "Zoro",
        year: "2024",
        caption: "Grit",
        image: "/work/manga2/zoro.jpg",
        alt: "Zoro in a green watercolor kimono sits calmly among falling cherry petals, with the word Patience in black script.",
      },
      {
        title: "Soul of Japan",
        year: "2024",
        caption: "Quiet",
        image: "/work/manga2/Soul_of_japan.jpg",
        alt: "Black-and-white samurai glowing with a white halo in front of a bushido quote on a dark, grainy background.",
      },
      {
        title: "Sicko",
        year: "2024",
        caption: "Dark",
        image: "/work/manga2/Sicko.jpg",
        alt: "Horned manga girl with long white hair curled into spirals, a black bar across her eyes and a red face, with SICKO in red letters below.",
      },
      {
        title: "Ronin",
        year: "2024",
        caption: "Alone",
        image: "/work/manga2/Ronin.jpg",
        alt: "Samurai in kabuki-style face paint walks down an old Japanese street, followed by fading ghost copies of himself.",
      },
    ],
    /**
     * 4 themed fan decks × 4 stills (16 total) — Chief lock 2026-09-11
     * Manga | Harmony | Prints | Universal (no photo/video fans)
     */
    fanDecks: [
      {
        theme: "Manga",
        faces: [
          { title: "Hebi", source: "manga", image: "/work/manga3/Hebi.jpg" },
          { title: "Kagurabachi", source: "manga", image: "/work/manga3/Kagurabachi.jpg" },
          { title: "Fire Force", source: "manga", image: "/work/manga3/Fire_Force.jpg" },
          { title: "Tanjiro", source: "manga", image: "/work/manga3/Tanjiro.jpg" },
        ],
      },
      {
        theme: "Harmony",
        faces: [
          { title: "Two Face Girl", source: "manga", image: "/work/manga2/Two_facegirl.jpg" },
          { title: "Love Figures", source: "manga", image: "/work/manga2/Love_Figures.jpg" },
          { title: "Lover", source: "manga", image: "/work/manga3/Lover.jpg" },
          { title: "Equal Sides", source: "manga", image: "/work/manga3/Equal_Sides.jpg" },
        ],
      },
      {
        theme: "Prints",
        faces: [
          { title: "Urban Skull", source: "print", image: "/work/fan/print-urban-skull.png" },
          { title: "Vagabond Ink", source: "print", image: "/work/fan/print-vagabond-ink.png" },
          { title: "Cyan Skeletons", source: "print", image: "/work/fan/print-cyan-skeletons.png" },
          { title: "Print 24", source: "print", image: "/work/fan/print-24.jpg" },
        ],
      },
      {
        theme: "Universal",
        faces: [
          { title: "Celestial X-Ray", source: "print", image: "/work/fan/print-celestial-xray.jpg" },
          { title: "Cosmic City", source: "print", image: "/work/fan/print-cosmic-city.jpg" },
          { title: "Cosmic Bamboo", source: "print", image: "/work/fan/print-cosmic-bamboo.jpg" },
          { title: "Mirage", source: "manga", image: "/work/manga3/Mirage0.jpg" },
        ],
      },
    ],
    /** Flat alias for older MangaSection readers — prefer fanDecks */
    fanDeck: [
      { title: "Hebi", source: "manga", theme: "Manga", image: "/work/manga3/Hebi.jpg" },
      { title: "Kagurabachi", source: "manga", theme: "Manga", image: "/work/manga3/Kagurabachi.jpg" },
      { title: "Fire Force", source: "manga", theme: "Manga", image: "/work/manga3/Fire_Force.jpg" },
      { title: "Tanjiro", source: "manga", theme: "Manga", image: "/work/manga3/Tanjiro.jpg" },
      { title: "Two Face Girl", source: "manga", theme: "Harmony", image: "/work/manga2/Two_facegirl.jpg" },
      { title: "Love Figures", source: "manga", theme: "Harmony", image: "/work/manga2/Love_Figures.jpg" },
      { title: "Lover", source: "manga", theme: "Harmony", image: "/work/manga3/Lover.jpg" },
      { title: "Equal Sides", source: "manga", theme: "Harmony", image: "/work/manga3/Equal_Sides.jpg" },
      { title: "Urban Skull", source: "print", theme: "Prints", image: "/work/fan/print-urban-skull.png" },
      { title: "Vagabond Ink", source: "print", theme: "Prints", image: "/work/fan/print-vagabond-ink.png" },
      { title: "Cyan Skeletons", source: "print", theme: "Prints", image: "/work/fan/print-cyan-skeletons.png" },
      { title: "Print 24", source: "print", theme: "Prints", image: "/work/fan/print-24.jpg" },
      { title: "Celestial X-Ray", source: "print", theme: "Universal", image: "/work/fan/print-celestial-xray.jpg" },
      { title: "Cosmic City", source: "print", theme: "Universal", image: "/work/fan/print-cosmic-city.jpg" },
      { title: "Cosmic Bamboo", source: "print", theme: "Universal", image: "/work/fan/print-cosmic-bamboo.jpg" },
      { title: "Mirage", source: "manga", theme: "Universal", image: "/work/manga3/Mirage0.jpg" },
    ],
  },

  /**
   * Photography chapter — after Manga; not Featured; NOT fan decks.
   * Homepage strip = flat curated stills; full 34 in Photography lane.
   * Assets: wix-photography-clean → public/work/photography/
   * SEE ALL → /work?lane=Photography
   */
  photography: {
    heading: "Photography",
    intro:
      "Street, ruin, and quiet light — frames that hold distance the way a panel holds a pause.",
    seeAll: "/work?lane=Photography",
    /** Homepage strip (flat / lightbox) — not fan decks */
    homepageCurated: [
      "Stone Towers",
      "Gold Hour Street",
      "City Overlook",
      "Paper Beast",
      "Safespeare",
      "Leaf Stairs",
      "Power Lines",
      "Bricks",
      "Statues",
      "Tree Canopy",
    ],
    items: [
      { title: "Italy Streets", year: "2023", caption: "Erase", image: "/work/photography/08_Italy_streets.jpg", alt: "Red no-entry street sign altered with a sticker figure carrying the white bar, against a sunlit ochre wall." },
      { title: "Safespeare", year: "2023", caption: "Stage", image: "/work/photography/09_Safespeare.jpg", alt: "Street paste-up of Shakespeare wearing red swim goggles, peeling on a warm yellow wall." },
      { title: "Panoramic", year: "2023", caption: "Wide", image: "/work/photography/10_Panoramic.jpg", alt: "Wide panorama of a riverside walkway and stone wall under clear blue sky, green hills across the water." },
      { title: "Loner Island", year: "2023", caption: "Alone", image: "/work/photography/11_Loner_Island.jpg", alt: "Black-and-white view of choppy water rolling toward a small dark wooded island." },
      { title: "Infinite Streets", year: "2023", caption: "Vanishing", image: "/work/photography/12_Infinite_Streets.jpg", alt: "Black-and-white narrow street between tall buildings, reflected in the glossy hood of a car." },
      { title: "Streets of Italy", year: "2023", caption: "Stone", image: "/work/photography/13_Streets_of_Italy.jpg", alt: "Wet cobblestone lane in cool shadow leading to a sunlit ochre church facade at the end." },
      { title: "Tunnels", year: "2023", caption: "Memory", image: "/work/photography/14_Tunnels.jpg", alt: "Two people stand at a railing beneath a weathered arched stone vault with an inscribed plaque, in black and white." },
      { title: "Clouds", year: "2023", caption: "Soft", image: "/work/photography/15_clouds.jpg", alt: "Black-and-white sky with a few bright clouds drifting above a dark tree line." },
      { title: "Lights", year: "2023", caption: "Single", image: "/work/photography/16_Lights.jpg", alt: "Single bare lightbulb glowing from a ceiling fixture in a dark, empty frame." },
      { title: "Statues", year: "2023", caption: "Still", image: "/work/photography/17_Statues.jpg", alt: "Weathered stone statue of a draped figure seen from below against bright green leaves." },
      { title: "Slink", year: "2023", caption: "Low", image: "/work/photography/18_Slink.jpg", alt: "Group of young men in matching white T-shirts pose together in a basement, one holding a speaker overhead." },
      { title: "Fantasy", year: "2023", caption: "Path", image: "/work/photography/19_Fantasy.jpg", alt: "Lush garden hillside of mossy green shrubs and pink blooms with a winding path and railing." },
      { title: "Bloom", year: "2023", caption: "Ember", image: "/work/photography/20_Bloom.jpg", alt: "Close-up of spiky red flowers among glossy green leaves in dappled light." },
      { title: "Paths", year: "2023", caption: "Lead", image: "/work/photography/21_Paths.jpg", alt: "Stone footpath curving through dense green ferns and trees in soft forest light." },
      { title: "Bricks", year: "2023", caption: "Texture", image: "/work/photography/22_Bricks.jpg", alt: "Close, angled black-and-white view of a patterned breeze-block wall receding into blur." },
      { title: "Sight", year: "2023", caption: "Look", image: "/work/photography/23_Sight.jpg", alt: "Black-and-white view through a crisscrossed iron railing toward a blurred bright canal." },
      { title: "Sidewalk", year: "2023", caption: "Ground", image: "/work/photography/24_Sidewalk.jpg", alt: "Pale paved sidewalk stretching ahead between tree trunks and bright red mulch, lined with long shadows." },
      { title: "Vineyard Hills", year: "2023", caption: "Frame", image: "/work/photography/01_IMG_0455.jpg", alt: "Rolling vineyard countryside under clear sky, a pond and blue pool below a wooden fence." },
      { title: "Stone Towers", year: "2023", caption: "Frame", image: "/work/photography/02_IMG_0441.jpg", alt: "Black-and-white hill town of medieval stone towers rising above tiled rooftops and trees." },
      { title: "Paper Beast", year: "2023", caption: "Frame", image: "/work/photography/03_IMG_0406.jpg", alt: "Blue and red cut-paper creature with polka dots stuck to a weathered cream wall." },
      { title: "Shadow Alley", year: "2023", caption: "Frame", image: "/work/photography/04_IMG_0380.jpg", alt: "Black-and-white narrow stone alley, one side lit by sun and the other lost in deep shadow." },
      { title: "Gold Hour Street", year: "2023", caption: "Frame", image: "/work/photography/05_IMG_0362.jpg", alt: "Sunlit city street with warm stone facades, parked cars and long shadows under a blue sky." },
      { title: "Summer Cove", year: "2023", caption: "Frame", image: "/work/photography/06_IMG_0601.jpg", alt: "Crowded sandy beach and rocks in a turquoise cove, green hills and white buildings above." },
      { title: "City Overlook", year: "2023", caption: "Frame", image: "/work/photography/07_IMG_0628.jpg", alt: "Black-and-white view from a tree-lined road over a sprawling city toward distant hills." },
      { title: "Power Lines", year: "2023", caption: "Archive", image: "/work/photography/25_photo_25.jpg", alt: "Black-and-white utility poles and crossing power lines against a sky of scattered clouds." },
      { title: "Leaf Stairs", year: "2023", caption: "Archive", image: "/work/photography/26_photo_26.jpg", alt: "Black-and-white wooden stairs climbing away, strewn with fallen leaves between dark foliage." },
      { title: "Hilltop Chair", year: "2023", caption: "Archive", image: "/work/photography/27_photo_27.jpg", alt: "Lone figure in a folding chair silhouetted on a dark rise against a white sky, beside a sign post." },
      { title: "Wild Yellow", year: "2023", caption: "Archive", image: "/work/photography/28_photo_28.jpg", alt: "Tall yellow wildflowers and green stalks glowing in sunlit woods." },
      { title: "Leaf Static", year: "2023", caption: "Archive", image: "/work/photography/29_photo_29.jpg", alt: "Dense black-and-white tangle of leaves, bright and dark in hard contrast." },
      { title: "Blossom Bench", year: "2023", caption: "Archive", image: "/work/photography/30_photo_30.jpg", alt: "Stone bench on a bluff above blue sea, framed by pink bougainvillea and red blossoms." },
      { title: "Tree Canopy", year: "2023", caption: "Archive", image: "/work/photography/31_photo_31.jpg", alt: "Black-and-white spreading tree canopy over palm fronds against a blank white sky." },
      { title: "Quiet Creek", year: "2023", caption: "Archive", image: "/work/photography/32_photo_32.jpg", alt: "Shaded green forest creek curving past a low stone wall where a person sits at the edge." },
      { title: "Night Tree", year: "2023", caption: "Archive", image: "/work/photography/33_photo_33.jpg", alt: "A single tree lit bright white against a near-black night sky." },
      { title: "Night Doors", year: "2023", caption: "Archive", image: "/work/photography/34_photo_34.jpg", alt: "Two lit brick entrances, an arched doorway and a shuttered window, floating in total darkness." },
    ],
  },

  /**
   * Videography chapter — after Photography; not Featured.
   * Assets: /workspace/wix-visualarts-assets/videos → public/work/videography/
   * Prefer mp4; skip near-dupes (Endless No Audio / Journey No Audio / journey.mp4).
   * SEE ALL → /work?lane=Videography
   */
  videography: {
    heading: "Videography",
    intro:
      "Personal motion work: 3D animation, edits, and music-led cuts. These are personal projects, not client reels.",
    seeAll: "/work?lane=Videography",
    /** Homepage strip: 4 (home unchanged; full lane has more) */
    homepageCurated: [
      "On Its Back",
      "Serpent Skull",
      "Low Sun",
      "Don't Waste Our Runaway",
    ],
    items: [
      {
        title: "On Its Back",
        year: "2026",
        caption: "3D animation",
        src: "/work/videography/cloud-fall.mp4",
        poster: "/work/videography/posters/cloud-fall.jpg",
        alt: "Faceless 3D figure in a gray jacket and navy jeans drifting on its back through pink sunset clouds.",
      },
      {
        title: "Serpent Skull",
        year: "2026",
        caption: "3D animation",
        src: "/work/videography/serpent-skull.mp4",
        poster: "/work/videography/posters/serpent-skull.jpg",
        alt: "White 3D skull in profile on dark navy, a small snake slithering through a crack in its crown.",
      },
      {
        title: "Stay Weird",
        year: "2026",
        caption: "Motion graphics",
        src: "/work/videography/stay-weird.mp4",
        poster: "/work/videography/posters/stay-weird.jpg",
        alt: "Teal wireframe cube around a shadowed face, with blurred stay weird text across the dark frame.",
      },
      {
        title: "5 Centimeters Edit",
        year: "2026",
        caption: "Anime edit",
        src: "/work/videography/5-centimeters-edit.mp4",
        poster: "/work/videography/posters/5-centimeters-edit.jpg",
        alt: "Anime-style sunlit stone pavement, cracked and dappled with leaf shadows and a soft pink light leak.",
      },
      {
        title: "Low Sun",
        year: "2026",
        caption: "3D animation",
        src: "/work/videography/red-horizon.mp4",
        poster: "/work/videography/posters/red-horizon.jpg",
        alt: "Dark angular craft flying low over pink dunes toward a pale sun, light streaks in an orange sky.",
      },
      {
        title: "Warhol's Flowers",
        year: "2024",
        caption: "Motion graphics",
        src: "/work/videography/Warhols Flowers.mp4",
        poster: "/work/videography/posters/warhols-flowers.jpg",
        alt: "Four-panel grid of the same roses tinted red, blue, magenta and green in matching frames on black.",
      },
      {
        title: "Euphoric Chant",
        year: "2024",
        caption: "Motion graphics",
        src: "/work/videography/Euphoric Chant.mp4",
        poster: "/work/videography/posters/euphoric-chant.jpg",
        alt: "White silhouette tumbling through dark blue space toward a bright glowing light.",
      },
      {
        title: "Don't Waste Our Runaway",
        year: "2024",
        caption: "Video edit",
        src: "/work/videography/Dont Waste our Runaway.mp4",
        poster: "/work/videography/posters/dont-waste-our-runaway.jpg",
        alt: "Silhouette carrying another person away from a fiery red and orange explosion at night.",
      },
      {
        title: "80s Weeknd",
        year: "2024",
        caption: "Video edit",
        src: "/work/videography/80s Weeknd.mp4",
        poster: "/work/videography/posters/80s-weeknd.jpg",
        alt: "Blurred silhouette and a diagonal shadow cast across a glowing red wall.",
      },
      {
        title: "Endless LoFi",
        year: "2024",
        caption: "Video edit",
        src: "/work/videography/Endless LoFi.mp4",
        poster: "/work/videography/posters/endless-lofi.jpg",
        alt: "Woman standing among commuters in a crowded subway car, seen through its open doors.",
      },
      {
        title: "Journeys",
        year: "2024",
        caption: "Video edit",
        src: "/work/videography/Journeys.mp4",
        poster: "/work/videography/posters/journeys.jpg",
        alt: "Rain-slick street at night reflecting streaks of neon pink, red and violet light.",
      },
      {
        title: "Flows",
        year: "2024",
        caption: "Video edit",
        src: "/work/videography/Flows.mp4",
        poster: "/work/videography/posters/flows.jpg",
        alt: "Group walking toward a green house under a blazing orange sunset sky.",
      },
      {
        title: "Razorhouse Go",
        year: "2024",
        caption: "Video edit",
        src: "/work/videography/Razorhouse Go.mp4",
        poster: "/work/videography/posters/razorhouse-go.jpg",
        alt: "Two young women asleep under dark blankets on pale pillows, with Razorhouse text in the corner.",
      },
    ],
  },

  /** Hero skull turntable — clockwise GLB; Coder wires (Chief lock 2026-09-18) */
  heroSkull: {
    model: "/work/3d/skull-turntable/skull.glb",
    href: "https://www.youtube.com/@theblackwallst97",
    ariaLabel: "YouTube — The Black Wall St",
    external: true,
  },

  /** Sitewide ambient bed — muted-first; Coder wires mute/play (Chief lock 2026-09-18) */
  audio: {
    src: "/work/audio/journeys-bed.mp3",
    label: "Journeys",
    /** Previous public bed — kept as backup */
    backupSrc: "/work/audio/endless-lofi-bed.mp3",
    mutedFirst: true,
    loop: true,
  },

  skills: {
    heading: "Skills",
    groups: [
      {
        title: "Design",
        items: [
          "Art direction",
          "Visual systems",
          "Typography",
          "Print & poster",
          "Brand identity",
        ],
      },
      {
        title: "Craft",
        items: [
          "Photoshop",
          "Manga / panel edits",
          "Merch & physical",
          "Texture & halftone",
          "Campaign tiles",
        ],
      },
      {
        title: "Process",
        items: [
          "Mood & caption",
          "Iteration",
          "Critique",
          "Asset systems",
          "Collaboration",
        ],
      },
    ],
  },

  contact: {
    heading: "Have a project in mind?",
    body: "Print, signage, apparel, brand, or a personal piece. Tell me what you're building and I'll get back to you.",
    cta: "Email me",
  },

  /**
   * Footer and contact links. Entries with an empty href are skipped, so a
   * new link can be added here before its URL is known.
   */
  social: [
    { label: "Email", href: "mailto:shonarip@gmail.com" },
    { label: "Instagram", href: "https://www.instagram.com/the_blackwall.st" },
    { label: "YouTube", href: "https://www.youtube.com/@theblackwallst97" },
    { label: "GitHub", href: "https://github.com/shonarip" },
  ],
} as const;

export type SiteContent = typeof site;
export type Discipline = (typeof site.disciplines)[number];
export type WorkFilter = (typeof site.workFilters)[number];
